### PR TITLE
Feature: draft for a dockerized Kaya RPC which tries to resolve #31

### LINKED ISSUE #31: Build Docker Image for Kaya RPC
Requirements:
- Be able to support _local_ Scilla development. This means that you need to compile the Scilla binaries within the docker files. You can refer to a reference implementation here
- Flag to toggle between `local` and `remote` mode
- Ability to specify the port for docker
- Able to toggle between verbose mode and normal mode. As well as fixtures. You need to be able to pass options to the Kaya RPC. (this might require some changes on the main Kaya RPC codebase)

Reference:
- Similar config files: Truffle-cli - https://github.com/trufflesuite/ganache-cli#docker 
- Building Scilla dependencies: https://github.com/Zilliqa/savant-ide/blob/545d132dab6cfe1e5931af5f29ed11847b5aac95/Dockerfile

### PR DESCRIPTION
**Pull request by visibilityspots**
## Description
An initial draft of a Dockerfile from which we could start to get to a proper docker image for Kaya RPC
Implementation of a dockerized Kaya RPC which could solve #31 

## Review Suggestion
- [x] initial draft
- [x] local development by building scilla-runner binary
- [x] local vs remote mode parameter
- [x] port as parameter
- [x] verbose vs normal mode parameter
- [ ] data volume for persistent data
- [x] publishing on docker hub
- [x] automated travis build
- [ ] dgoss serverspec tests
- [ ] update documentation

## Status
Initial draft

### Implementation
as for now I used my own account to demo the way travis could pick up changes automatically and push them to docker hub.
Once confirmed for merge this should obviously go under a Zilliqa docker account.

### CODE REVIEW

**Comment by Qkyrie** [comment]
Hi @visibilityspots, any blocking issues?

**Comment by visibilityspots** [comment]
Hi @Qkyrie I fought a bit with the local scilla setup but in the end it seemed to be the upstream node:10.11.1-slim image which was based on debian jessie and pulled in some older versions.

With the debian stretch image of node it works like I expected it to be.

I updated the README for the behaviour with the asked features. Let me know if there are some remarks so I could try to adapt the docker image build.

As soon as the features are all met and proved to be working the travis step could be updated so travis will take care of the docker image build process in combination with an automated docker image build on docker hub under a @Zilliqa organisation

**Comment by karelstriegel** [comment]
> I updated the README for the behavior with the asked features. Let me know if there are some remarks so I could try to adapt the docker image build.

@edisonljh can you have a look?

**Comment by edisonljh** [comment]
Awesome work so far @visibilityspots . Would mind updating the docker file to the latest master branch that I just pushed a few hours ago? Might require some small change on the folders and config flags.

Thanks! 

Cc : @karelstriegel

**Comment by visibilityspots** [comment]
@edisonljh I just merged upstream/master but unfortunately some tests are failing in kaya currently on master :( https://travis-ci.com/Zilliqa/kaya/builds.
As soon as those got fixed I could merge master branch again..

**Comment by edisonljh** [comment]
@visibilityspots If you run `npm test`, does it pass? Do not have to worry about the travis tests, that's my fault and I will get it fixed sometime soon.

**Comment by visibilityspots** [comment]
@edisonljh alright so I disabled the npm test step in the .travis.yml file for now so the travis run on my fork will work fine.

Locally it all works fine by building the docker image with docker build.

**Comment by edisonljh** [comment]
@visibilityspots We are happy with the solution. Thanks for contributing! Some of the things can't be tested now so we will merge it to a separate branch first. Thanks @visibilityspots!

**Comment by visibilityspots** [comment]
Hi @edisonljh nice to hear I could help you guys out, don't forget to adjust the .travis.yml file when merging into master.

I described the process to generate the docker hub image on https://visibilityspots.org/docker-openstackclient-kilo.html

**Comment by karelstriegel** [comment]
> which could solve #31

Hey @visibilityspots this is the reason why auto claim is not working. The official keywords are :

- close
- closes
- closed
- fix
- fixes
- fixed
- resolve
- resolves
- resolved

**Pull request merged**
